# Generated by Django 5.0.1 on 2024-11-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='status',
            field=models.BooleanField(choices=[(True, 'Disponível'), (False, 'Indisponível')], default=True, verbose_name='Status'),
        ),
    ]
