# Generated by Django 5.0.1 on 2024-11-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('AC', 'Ação'), ('CO', 'Comédia'), ('DR', 'Drama'), ('FA', 'Fantasia'), ('RO', 'Romance'), ('TE', 'Terror'), ('FI', 'Ficção'), ('PO', 'Policial')], max_length=2, verbose_name='Gênero'),
        ),
    ]
