# Generated by Django 5.1.2 on 2024-11-05 20:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(default=datetime.date.today, verbose_name='Data do Empréstimo')),
                ('data_devolucao_prevista', models.DateField(verbose_name='Data de Devolução Prevista')),
                ('status', models.CharField(choices=[('AB', 'Em Aberto'), ('CO', 'Concluído')], default='AB', max_length=2, verbose_name='Status do Empréstimo')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro', verbose_name='Livro')),
            ],
        ),
    ]
